export default {
  products: [
    {
      _id: '1',
      name: 'CBD Product 1',
      category: 'cbdproducts',
      image: '/images/product-1.jpg',
      price: 50,
      brand: 'Spectrum',
      rating: 0.5,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: '2',
      name: 'CBD Product 2',
      category: 'cbdproducts',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Spectrum',
      rating: 1,
      numReviews: 51,
      countInStock: 13,
    },
    {
      _id: '3',
      name: 'CBD Product 3',
      category: 'cbdproducts',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Spectrum',
      rating: 2,
      numReviews: 45,
      countInStock: 46,
    },
    {
      _id: '4',
      name: 'CBD Product 4',
      category: 'cbdproducts',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Spectrum',
      rating: 2.5,
      numReviews: 198,
      countInStock: 56,
    },
    {
      _id: '5',
      name: 'CBD Product 5',
      category: 'cbdproducts',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Spectrum',
      rating: 3,
      numReviews: 89,
      countInStock: 126,
    },
    {
      _id: '6',
      name: 'CBD Product 6',
      category: 'cbdproducts',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Spectrum',
      rating: 4,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: '7',
      name: 'CBD Product 7',
      category: 'cbdproducts',
      image: '/images/product-7.jpg',
      price: 32,
      brand: 'Spectrum',
      rating: 5,
      numReviews: 1333,
      countInStock: 2,
    },
  ],
};
