export default{
    products:[{
        _id:'1',
        name:'CBD drops',
        category:'CBD Oil',
        image:'/images/product-1.jpg',
        price:233,
        brand:'Spectrum',
        rating:4.5,
        numReviews:13,
        countInStock:2,
    },
    {
        _id:'2',
        name:'CBD drops',
        category:'CBD Oil',
        image:'/images/product-2.jpg',
        price:64,
        brand:'Spectrum',
        rating:3,
        numReviews:434,
        countInStock:34,
    },
    {
        _id:'3',
        name:'CBD drops',
        category:'CBD Oil',
        image:'/images/product-1.jpg',
        price:604,
        brand:'Spectrum',
        rating:5,
        numReviews:234,
        countInStock:33,
    },
    {
        _id:'4',
        name:'CBD drops',
        category:'CBD Oil',
        image:'/images/product-1.jpg',
        price:62,
        brand:'Spectrum',
        rating:3,
        numReviews:13,
        countInStock:4,
    },
    {
        _id:'5',
        name:'CBD drops',
        category:'CBD Oil',
        image:'/images/product-1.jpg',
        price:44,
        brand:'Spectrum',
        rating:4,
        numReviews:44,
        countInStock:9,
    },
    {
        _id:'6',
        name:'CBD drops',
        category:'CBD Oil',
        image:'/images/product-1.jpg',
        price:44,
        brand:'Spectrum',
        rating:5,
        numReviews:34,
        countInStock:2,
    },
    ],
};